version: '3.8'

services:
  flask_app:
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Proba
    ports:
      - "5432:5432"
  
